[theme]
primaryColor = "#DC143C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[server]
port = 8501
headless = true
maxUploadSize = 200
enableXsrfProtection = true

[logger]
level = "info"
